name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ci:
    uses: igor-siergiej/im-apps-utils/.github/workflows/ci.yml@main

  build:
    needs: ci
    uses: igor-siergiej/im-apps-utils/.github/workflows/docker-build.yml@main
    with:
      app_name: shoppingo
      registry: 192.168.68.54:31834

  gitops:
    needs: build
    uses: igor-siergiej/im-apps-utils/.github/workflows/gitops-update.yml@main
    with:
      app_name: shoppingo
      registry: 192.168.68.54:31834
      version: ${{ needs.build.outputs.version }}
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}